CREATE TABLE employee (
  EMP_ID VARCHAR(5) PRIMARY KEY,
  NAME VARCHAR(50),
  EMAIL VARCHAR(100),
  FLOOR_SEAT_SEQ INT
);

CREATE TABLE seating_chart (
  FLOOR_SEAT_SEQ INT PRIMARY KEY AUTO_INCREMENT,
  FLOOR_NO INT,
  SEAT_NO VARCHAR(10)
);
